jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8083
   servlet:
      context-path: /reserva
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://localhost:1433;databasename=you-home
      username: sa
      password: $admin.domain.
   jpa:
      database: sql-server
      hibernate:
         ddl-auto: update
      show-sql: false
